development:
  adapter: postgresql
  encoding: unicode
  database: lynne_campbell_artist_development
  pool: 5
  username: charlie
  password:
  timeout: 5000

test:
  adapter: postgresql
  encoding: unicode
  database: lynne_campbell_artist_test
  pool: 5
  username: charlie
  password:
  timeout: 5000